force-app/main/default/objects/Case/fields/CaseExternalUI__c.field-meta.xml
<CustomField>
    <fullName>CaseExternalUI__c</fullName>
    <description>This UUID is being used to identify our cases from external systems.</description>
    <externalId>true</externalId>
    <label>CaseExternalUID</label>
    <length>6</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/ATM_Fee_in_other_currencies__c.field-meta.xml
<CustomField>
    <fullName>ATM_Fee_in_other_currencies__c</fullName>
    <description>Fee that customer pays withdrawing money from other currencies than their card currency.</description>
    <formula>IF( OR(ISBLANK(Product__c),ISBLANK(Home_Country__c)), &quot;-&quot;, IF(Product__r.Name = &apos;Standard&apos;, &quot;1.7%&quot;, &quot;Free&quot;)
)</formula>
    <label>ATM Fee in other currencies</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Card_Replacement_Cost__c.field-meta.xml
<CustomField>
    <fullName>Card_Replacement_Cost__c</fullName>
    <description>Amount of money that customer should pay in case of the replacement of their card.</description>
    <formula>IF( OR(ISBLANK(Product__c),ISBLANK(Home_Country__c)), &quot;-&quot;, IF( Product__r.Name = &apos;Metal&apos;, TEXT(Home_Country__r.Currency_Symbol__c) + &quot;45&quot;, TEXT(Home_Country__r.Currency_Symbol__c) + &quot;6&quot;))</formula>
    <label>Card Replacement Cost</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Cost_per_Calendar_Month__c.field-meta.xml
<CustomField>
    <fullName>Cost_per_Calendar_Month__c</fullName>
    <description>Amount of money customer pays on monthly basis.</description>
    <formula>IF( OR(ISBLANK(Product__c), ISBLANK(Home_Country__c)) , &quot;-&quot;, IF(Product__r.Name = &apos;Standard&apos;, TEXT(Home_Country__r.Currency_Symbol__c) + &quot;0&quot;,  
   IF(AND(Product__r.Name = &apos;Black&apos;, Home_Country__r.Name &lt;&gt; &apos;UK&apos;), TEXT(Home_Country__r.Currency_Symbol__c) + &quot;9.90&quot;, 
   IF(AND(Product__r.Name = &apos;Metal&apos;, Home_Country__r.Name &lt;&gt; &apos;UK&apos;), TEXT(Home_Country__r.Currency_Symbol__c) + &quot;16.90&quot;, &apos;N/a&apos;))
)
)</formula>
    <label>Cost per Calendar Month</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Home_Country__c.field-meta.xml
<CustomField>
    <fullName>Home_Country__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Home Country</label>
    <referenceTo>Home_Country__c</referenceTo>
    <relationshipLabel>Contacts</relationshipLabel>
    <relationshipName>Contacts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <referenceTo>Product__c</referenceTo>
    <relationshipLabel>Contacts</relationshipLabel>
    <relationshipName>Contacts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Home_Country__c/Home_Country__c.object-meta.xml
<CustomObject>
    <label>Home Country</label>
    <nameField>
        <label>Home Country Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Home Countries</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Home_Country__c/fields/Currency_Symbol__c.field-meta.xml
<CustomField>
    <fullName>Currency_Symbol__c</fullName>
    <description>It shows the currency symbol of the specific country.</description>
    <label>Currency Symbol</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>€</fullName>
            </value>
            <value>
                <fullName>£</fullName>
            </value>
            <value>
                <fullName>$</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product__c/Product__c.object-meta.xml
<CustomObject>
    <label>Product</label>
    <nameField>
        <label>Product Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Products</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/CaseServiceHandler_TEST.cls
@IsTest
private class CaseServiceHandler_TEST {

    @testSetup
    static void testSetup() {
        // Test Product
        Product__c testProd = new Product__c(Name = 'Standard');
        insert testProd;

        // Test Home Country
        Home_Country__c testHC = new Home_Country__c(Name = 'DE', Currency_Symbol__c = '€');
        insert testHC;

        // Test Contact
        Contact testContact = new Contact(LastName = 'N26 User', Product__c = testProd.Id, Home_Country__c = testHC.Id);
        insert testContact;

        // Test Case with the data above
        Case testCase = new Case(ContactId = testContact.Id, Status = 'New', Subject = 'Test WEB Service', CaseExternalUI__c = 'A1B2C3');
        insert testCase;
    }

    /**
     * Test the happy path where the ExternalId received exists in our system
     */
    static testMethod void testSuccess() {
        Case existingCase = [SELECT Id,Contact.Product__r.Name,Contact.Home_Country__r.Name,
                             Contact.ATM_Fee_in_other_currencies__c,Contact.Cost_per_Calendar_Month__c,
                             Contact.Card_Replacement_Cost__c
                             FROM Case WHERE CaseExternalUI__c = 'A1B2C3']; // Case that is inserted into database in setup method

        // Preparing the REST call with a valid caseExternal
        RestRequest req = new RestRequest();
        RestResponse res = new RestResponse();
        req.requestURI = '/services/apexrest/CaseDetails';
        req.httpMethod = 'GET';
        req.addParameter('caseExternal', 'A1B2C3');
        RestContext.request = req;
        RestContext.response = res;

        Test.startTest();
        Case resultCase = CaseServiceHandler.getCase();
        system.assertEquals(existingCase.Id, resultCase.Id);
        system.assertEquals(existingCase.ContactId, resultCase.ContactId);
        system.assertEquals(existingCase.Contact.ATM_Fee_in_other_currencies__c, resultCase.Contact.ATM_Fee_in_other_currencies__c);
        system.assertEquals(existingCase.Contact.Cost_per_Calendar_Month__c, resultCase.Contact.Cost_per_Calendar_Month__c);
        system.assertEquals(existingCase.Contact.Cost_per_Calendar_Month__c, resultCase.Contact.Cost_per_Calendar_Month__c);
        system.assertEquals(existingCase.Contact.Home_Country__r, resultCase.Contact.Home_Country__r);
        system.assertEquals(existingCase.Contact.Product__r, resultCase.Contact.Product__r);
        Test.stopTest();
    }

    /**
     * Test API when the ExternalId does not exist in our system
     */
    static testMethod void testFail01() {
        // Preparing the REST call with an invalid caseExternal
        RestRequest req = new RestRequest();
        RestResponse res = new RestResponse();
        req.requestURI = '/services/apexrest/CaseDetails';
        req.httpMethod = 'GET';
        req.addParameter('caseExternal', 'ABC123');
        RestContext.request = req;
        RestContext.response = res;

        Test.startTest();
        Case resultCase = CaseServiceHandler.getCase();
        system.assertEquals(null, resultCase);
        system.assertEquals(400, res.StatusCode);
        Test.stopTest();
    }

    /**
     * Test API when the ExternalId is not a valid (length is not 6).
     */
    static testMethod void testFail02() {
        // Preparing the REST call with an invalid caseExternal
        RestRequest req = new RestRequest();
        RestResponse res = new RestResponse();
        req.requestURI = '/services/apexrest/CaseDetails';
        req.httpMethod = 'GET';
        req.addParameter('caseExternal', 'ABCD1234');
        RestContext.request = req;
        RestContext.response = res;

        Test.startTest();
        Case resultCase = CaseServiceHandler.getCase();
        system.assertEquals(null, resultCase);
        system.assertEquals(406, res.StatusCode);
        Test.stopTest();
    }

}