force-app/main/default/objects/Case/fields/CaseExternalUI__c.field-meta.xml
<CustomField>
    <fullName>CaseExternalUI__c</fullName>
    <description>This UUID is being used to identify our cases from external systems.</description>
    <externalId>true</externalId>
    <label>CaseExternalUID</label>
    <length>6</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/ATM_Fee_in_other_currencies__c.field-meta.xml
<CustomField>
    <fullName>ATM_Fee_in_other_currencies__c</fullName>
    <description>Fee that customer pays withdrawing money from other currencies than their card currency.</description>
    <formula>IF( OR(ISBLANK(Product__c),ISBLANK(Home_Country__c)), &quot;-&quot;, IF(Product__r.Name = &apos;Standard&apos;, &quot;1.7%&quot;, &quot;Free&quot;)
)</formula>
    <label>ATM Fee in other currencies</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Card_Replacement_Cost__c.field-meta.xml
<CustomField>
    <fullName>Card_Replacement_Cost__c</fullName>
    <description>Amount of money that customer should pay in case of the replacement of their card.</description>
    <formula>IF( OR(ISBLANK(Product__c),ISBLANK(Home_Country__c)), &quot;-&quot;, IF( Product__r.Name = &apos;Metal&apos;, TEXT(Home_Country__r.Currency_Symbol__c) + &quot;45&quot;, TEXT(Home_Country__r.Currency_Symbol__c) + &quot;6&quot;))</formula>
    <label>Card Replacement Cost</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Cost_per_Calendar_Month__c.field-meta.xml
<CustomField>
    <fullName>Cost_per_Calendar_Month__c</fullName>
    <description>Amount of money customer pays on monthly basis.</description>
    <formula>IF( OR(ISBLANK(Product__c), ISBLANK(Home_Country__c)) , &quot;-&quot;, IF(Product__r.Name = &apos;Standard&apos;, TEXT(Home_Country__r.Currency_Symbol__c) + &quot;0&quot;,  
   IF(AND(Product__r.Name = &apos;Black&apos;, Home_Country__r.Name &lt;&gt; &apos;UK&apos;), TEXT(Home_Country__r.Currency_Symbol__c) + &quot;9.90&quot;, 
   IF(AND(Product__r.Name = &apos;Metal&apos;, Home_Country__r.Name &lt;&gt; &apos;UK&apos;), TEXT(Home_Country__r.Currency_Symbol__c) + &quot;16.90&quot;, &apos;N/a&apos;))
)
)</formula>
    <label>Cost per Calendar Month</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Home_Country__c.field-meta.xml
<CustomField>
    <fullName>Home_Country__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Home Country</label>
    <referenceTo>Home_Country__c</referenceTo>
    <relationshipLabel>Contacts</relationshipLabel>
    <relationshipName>Contacts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <referenceTo>Product__c</referenceTo>
    <relationshipLabel>Contacts</relationshipLabel>
    <relationshipName>Contacts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Home_Country__c/Home_Country__c.object-meta.xml
<CustomObject>
    <label>Home Country</label>
    <nameField>
        <label>Home Country Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Home Countries</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Product__c/Product__c.object-meta.xml
<CustomObject>
    <label>Product</label>
    <nameField>
        <label>Product Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Products</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/CaseServiceHandler.cls
/**
 * Author: RH on 01/08/2020
 * It is providing the case details to an external system
 * TestClass: CaseServiceHandler_TEST
 */

@RestResource(urlMapping='/CaseDetails')
global with sharing class CaseServiceHandler {

    @HttpGet
    global static Case getCase(){
        String caseExternalId;
        RestRequest req = RestContext.request; // Request from the external system
        RestResponse res = RestContext.response; // Response sent to the external system

        if (req.params.containsKey('caseExternal')) caseExternalId = req.params.get('caseExternal');

        // Check if the external id is not empty and if the length 6, otherwise respond as an error
        if (caseExternalId == null || caseExternalId.length() != 6) {
          res.StatusCode = 406;
          res.addHeader('Error', 'caseExternal is not valid.');
          return null;
        }

        // Retreive the case with the external id retreived above
        system.debug('*** INFO: caseExternal: ' + caseExternalId + ' ***');
        try {
            List<Case> foundCase = [SELECT Id,Contact.Product__r.Name,Contact.Home_Country__r.Name,
                             Contact.ATM_Fee_in_other_currencies__c,Contact.Cost_per_Calendar_Month__c,
                             Contact.Card_Replacement_Cost__c
                             FROM Case WHERE CaseExternalUI__c =: caseExternalId LIMIT 1];

            // Case is found and sent back to the external system
            if (foundCase.size() > 0){
                res.addHeader('Content-Type', 'application/json');
                res.StatusCode = 200;
                return foundCase[0];
            } else {
                res.StatusCode = 400;
                res.addHeader('Error', 'There is no Case found with such caseExternal in our system.');
                return null;
            }

        } catch (Exception e) {
            res.statusCode = 500;
            res.addHeader('Error', e.getMessage());
            system.debug('*** ERRRO at line: ' + e.getStackTraceString() + ' Message: ' + e.getMessage() + ' ***');
            return null;
        }
    }

}