force-app/main/default/objects/Contact/fields/ATM_Fee_in_other_currencies__c.field-meta.xml
<CustomField>
    <fullName>ATM_Fee_in_other_currencies__c</fullName>
    <description>Fee that customer pays withdrawing money from other currencies than their card currency.</description>
    <formula>IF( OR(ISBLANK(Product__c),ISBLANK(Home_Country__c)), &quot;-&quot;, IF(Product__r.Name = &apos;Standard&apos;, &quot;1.7%&quot;, &quot;Free&quot;)
)</formula>
    <label>ATM Fee in other currencies</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Card_Replacement_Cost__c.field-meta.xml
<CustomField>
    <fullName>Card_Replacement_Cost__c</fullName>
    <description>Amount of money that customer should pay in case of the replacement of their card.</description>
    <formula>IF( OR(ISBLANK(Product__c),ISBLANK(Home_Country__c)), &quot;-&quot;, IF( Product__r.Name = &apos;Metal&apos;, TEXT(Home_Country__r.Currency_Symbol__c) + &quot;45&quot;, TEXT(Home_Country__r.Currency_Symbol__c) + &quot;6&quot;))</formula>
    <label>Card Replacement Cost</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Cost_per_Calendar_Month__c.field-meta.xml
<CustomField>
    <fullName>Cost_per_Calendar_Month__c</fullName>
    <description>Amount of money customer pays on monthly basis.</description>
    <formula>IF( OR(ISBLANK(Product__c), ISBLANK(Home_Country__c)) , &quot;-&quot;, IF(Product__r.Name = &apos;Standard&apos;, TEXT(Home_Country__r.Currency_Symbol__c) + &quot;0&quot;,  
   IF(AND(Product__r.Name = &apos;Black&apos;, Home_Country__r.Name &lt;&gt; &apos;UK&apos;), TEXT(Home_Country__r.Currency_Symbol__c) + &quot;9.90&quot;, 
   IF(AND(Product__r.Name = &apos;Metal&apos;, Home_Country__r.Name &lt;&gt; &apos;UK&apos;), TEXT(Home_Country__r.Currency_Symbol__c) + &quot;16.90&quot;, &apos;N/a&apos;))
)
)</formula>
    <label>Cost per Calendar Month</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Home_Country__c.field-meta.xml
<CustomField>
    <fullName>Home_Country__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Home Country</label>
    <referenceTo>Home_Country__c</referenceTo>
    <relationshipLabel>Contacts</relationshipLabel>
    <relationshipName>Contacts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <referenceTo>Product__c</referenceTo>
    <relationshipLabel>Contacts</relationshipLabel>
    <relationshipName>Contacts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Home_Country__c/Home_Country__c.object-meta.xml
<CustomObject>
    <label>Home Country</label>
    <nameField>
        <label>Home Country Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Home Countries</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Product__c/Product__c.object-meta.xml
<CustomObject>
    <label>Product</label>
    <nameField>
        <label>Product Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Products</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/CustomerDataWrapper.cls
/**
 * Author: RH on 01/08/2020.
 * It is used for the Case object.
 * Provoked from: Case_AgentHelper_Controller
 * TestClass: CaseServiceHandler_TEST
 */

public class CustomerDataWrapper {
    @AuraEnabled
    public String productType  {get;set;} //They should have @AuraEnabled because the attributes are used in a lightning component.
    @AuraEnabled
    public String homeCountry  {get;set;}
    @AuraEnabled
    public String costPerMonth {get;set;}
    @AuraEnabled
    public String atmFee       {get;set;}
    @AuraEnabled
    public String cardReplace  {get;set;}

    /**
     * Receives a case record and returns the data related to its contact. If the "Product Type" or "Home Country" are not set in the contact
     * we set their values equal to "Not Set"
     */
    public CustomerDataWrapper(Case thisCase){
        this.productType = thisCase.Contact.Product__r != NULL ? thisCase.Contact.Product__r.Name : 'Not Set';
        this.homeCountry = thisCase.Contact.Home_Country__r != NULL ? thisCase.Contact.Home_Country__r.Name : 'Not Set';
        this.costPerMonth = thisCase.Contact.Cost_per_Calendar_Month__c;
        this.atmFee = thisCase.Contact.ATM_Fee_in_other_currencies__c;
        this.cardReplace = thisCase.Contact.Card_Replacement_Cost__c;
    }
}